version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8080:8000
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - app/.env

volumes:
  postgres_data:
